#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  application:
    name: eureka-client
server:
  port: 2004
#属性对应服务注册中心的配置内容，指定服务注册中心的位置(服务注册到集群注册中心)
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
      
#      http://peer1:1111/eureka/
#      ,http://peer2:1112/eureka/