#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0
      
server:
  port: 2002
#属性对应服务注册中心的配置内容，指定服务注册中心的位置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
#       defaultZone: http://eureka.neunb.rd/eureka/